### ISSUE TITLE
Question about ELBO Computation

### ISSUE THREAD

**Issue by RuihongQiu** [federicobergamin/Variational-Inference-with-Normalizing-Flows#1]
Hi @federicobergamin,

Thank you for sharing this great repo of VI with NF.

I have a question about the implementation of the ELBO.
At [line 271 of the VAE_with_NF model](https://github.com/federicobergamin/Variational-Inference-with-Normalizing-Flows/blob/09c3702a4ae04d044bc9bfefa20de5078a44caab/VAE_with_flows.py#L271), why do we need to calculate the `z_k` under a standard normal. I don't get this idea from the ELBO of the [VI with NF paper](https://arxiv.org/pdf/1505.05770.pdf)
![image](https://user-images.githubusercontent.com/17882988/85363619-b2d6cc80-b564-11ea-9d4c-a5b44bdaf8ae.png)

I cannot see any term indicating we need to calculate the probability of `z_k` under a standard normal.

I have also joined the discussion in [this issue](https://github.com/riannevdberg/sylvester-flows/issues/4). I have been really frustrated about this `z_k` term in ELBO.

Could you explain it a little bit? Many thanks!

**Comment by RuihongQiu** [comment]
I have got answer there. Still thanks for this repo!

**Comment by federicobergamin** [comment]
Hi @RuihongQiu , sorry if I did not answer you before. 
Happy that you got some clarification in the other thread from Rianne, which for sure knows this whole topic better than me :)
